# Generated by Django 5.2.1 on 2025-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.TextField()),
                ('audit_manager', models.TextField(blank=True, null=True)),
                ('Partner', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.TextField()),
                ('audit_manager', models.TextField(blank=True, null=True)),
                ('Partner', models.TextField(blank=True, null=True)),
                ('Admin', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employee_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fullday_halfday', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planning',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField()),
                ('Password', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
